development:
  name: pin-app-adapter
  url: http://dev.app-adapter.2010.mindpin.com/
  master_url: http://dev.config-manager.2010.mindpin.com/

test:
  name: pin-app-adapter
  url: http://dev.app-adapter.2010.mindpin.com/
  master_url: http://dev.config-manager.2010.mindpin.com/

production:
  name: pin-app-adapter
  url: http://app-adapter.2010.mindpin.com/
  master_url: http://dev.config-manager.2010.mindpin.com/